version: "3.3"
services:
  web:
    container_name: pa11
    build: .
    depends_on:
      - postgres
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
      TEST_SQLALCHEMY_DATABASE_URI: ${TEST_SQLALCHEMY_DATABASE_URI}
      LC_ALL: ${LC_ALL}
      LANG: ${LANG}
    ports:
        - "5000:5000"
    restart: always
    volumes:
        - .:/pa
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - "5432:5432"
    restart: always
    volumes:
        - ./db_data:/var/lib/postgresql/data
