"""relationship between asset and record has been added

Revision ID: 86569d164c58
Revises: 083123b67ef1
Create Date: 2019-10-05 02:17:49.096246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86569d164c58'
down_revision = '083123b67ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'record', 'asset', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_column('record', 'asset_id')
    # ### end Alembic commands ###
