"""initial db migration

Revision ID: 8d5037cb1644
Revises: 
Create Date: 2019-10-27 22:34:05.222593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d5037cb1644'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'UAH', 'CRB', 'XAG', 'EUR', name='currency'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_currency'), 'asset', ['currency'], unique=False)
    op.create_index(op.f('ix_asset_name'), 'asset', ['name'], unique=False)
    op.create_table('inflation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inflation_date'), 'inflation', ['date'], unique=False)
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_replenish', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_date'), 'record', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_date'), table_name='record')
    op.drop_table('record')
    op.drop_index(op.f('ix_inflation_date'), table_name='inflation')
    op.drop_table('inflation')
    op.drop_index(op.f('ix_asset_name'), table_name='asset')
    op.drop_index(op.f('ix_asset_currency'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
